spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/postshubdb
spring.datasource.username=postshub
spring.datasource.password=postshub
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

jwt.secret-key=Y4g4jLJr1x9dP5v5Ih4o8lM6lA6jN8qS8uVv9cJwW0I=
jwt.issuer=postshub
jwt.token.expires-in=300
jwt.refresh-token.expires-in=86400